# -*- coding: utf-8 -*-
"""Copy of HeartDiseasePredictInPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MDmy-UXWpSZ_bctCx9ZW1fY3O9xXcap4
"""

#وارد کردن کتابخانه ها
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import seaborn as sns

heart_data = pd.read_csv('/content/heart.csv')

heart_data.head()

heart_data.shape

heart_data.info()

heart_data.isnull().sum()

heart_data.describe()

#چند ردیف با تارگت 0 و چند ردیف با تارگت 1 داریم
heart_data['target'].value_counts()

#جدا سازی سایر ویژگی ها از تارگت
X = heart_data.drop(columns='target')
Y = heart_data['target']

print(X)

print(Y)

#یافتن همبستگی بین صفات 
plt.figure(figsize=(30,10))
sns.heatmap(heart_data.corr(), annot=True, cmap='terrain')

#جداسازی داده های آموزشی از آزمایشی
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

model = LogisticRegression()

model.fit(X_train, Y_train)

#آموزش داده ها با accuracy
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('دقت در داده های آموزشی : ', training_data_accuracy*100)

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('دقت در داده های آزمایشی : ', test_data_accuracy*100)

#نمونه داده
input_data = (55,1,0,160,289,0,0,145,1,0.8,1,1,3)

# تغییر داده های ورودی نمونه به آرایه numpy
input_data_as_numpy_array= np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('شخص بیماری قلبی ندارد')
else:
  print('شخص بیماری قلبی دارد')